### ISSUE TITLE
Alembic support

### ISSUE THREAD

**Issue by kimdre** [dorosch/sqlalchemy-timescaledb#13]
Hi, is it possible to use this with alembic?

**Comment by dorosch** [comment]
Hi @kimdre,

Yes it's possible - https://github.com/dorosch/sqlalchemy-timescaledb/blob/master/sqlalchemy_timescaledb/dialect.py#L13

**Comment by kimdre** [comment]
Thanks, do you need to specify the hypertable paramaters manually in the migration? I noticed that when I try to autogenerate a migration these hypertable parameters weren't added/included to the migration file.

E.g. like so:

Parameter
```python
__table_args__ = ({
        'timescaledb_hypertable': {
            'time_column_name': 'ts'
        }
    })
```

Migration
```python
op.create_table(
        TABLE_NAME,
        sa.Column('ts', sa.DateTime),
        sa.Column('col1', sa.String(50)),
        sa.Column('col2', sa.String(50)),
        schema=SCHEMA,
        if_not_exists=True,)

    op.execute(f"SELECT create_hypertable('{SCHEMA}.{TABLE_NAME}', 'ts');")
```

**Comment by dorosch** [comment]
Actually, there is no such way as the [built-in mechanism](https://github.com/dorosch/sqlalchemy-timescaledb/blob/master/sqlalchemy_timescaledb/dialect.py#L18) is used to support hypertables. It is necessary to [perform sql command](https://github.com/dorosch/sqlalchemy-timescaledb/blob/master/sqlalchemy_timescaledb/dialect.py#L47), which is difficult to add in migration, to create a table.

If you have any additional questions, please let me know
