### ISSUE TITLE
how to use 'chunk_time_interval' parameter

### ISSUE THREAD

**Issue by vssssssssss** [dorosch/sqlalchemy-timescaledb#8]
Could you please explain me how to use 'chunk_time_interval'?

I've tried below but it didn't work.

  timescaledb_hypertable={
        'time_column_name': 'time',
        'chunk_time_interval': '7 days',
    }

If create a table and after that I convert it to a hypertable in a normal SQLAlchemy ways, it works though.

Thank you!

**Comment by dorosch** [comment]
Hello @vssssssssss , thanks for the question. Here is a working example using the library:
```python
import datetime

from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Float, String, DateTime

Base = declarative_base()

class Metric(Base):
    __table_args__ = ({
        'timescaledb_hypertable': {
            'time_column_name': 'timestamp',
            'chunk_time_interval': '7 days'
        }
    })

    name = Column(String)
    value = Column(Float)
    timestamp = Column(
        DateTime(), default=datetime.datetime.now, primary_key=True
    )
```

A slightly non-obvious point is that the hypertable is created after the creation of the original table: https://github.com/dorosch/sqlalchemy-timescaledb/blob/master/sqlalchemy_timescaledb/dialect.py#L18

This means that all changes to the hypertable are applied at the time the original table is created.

I hope this answers your question. If you have any more questions please let me know.
